# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user/user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/user/user.proto',
  package='user',
  syntax='proto3',
  serialized_pb=_b('\n\x15proto/user/user.proto\x12\x04user\"6\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\x05\"(\n\x07\x44\x61taRes\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"<\n\nAddUserReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\x05\"P\n\rUpdateUserReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\x05\" \n\rDeleteUserReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x32\x9f\x01\n\x07UserApi\x12,\n\x07\x61\x64\x64User\x12\x10.user.AddUserReq\x1a\r.user.DataRes\"\x00\x12\x32\n\nupdateUser\x12\x13.user.UpdateUserReq\x1a\r.user.DataRes\"\x00\x12\x32\n\ndeleteUser\x12\x13.user.DeleteUserReq\x1a\r.user.DataRes\"\x00\x62\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='user.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='user.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='user.User.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='user.User.gender', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=85,
)


_DATARES = _descriptor.Descriptor(
  name='DataRes',
  full_name='user.DataRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='user.DataRes.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='user.DataRes.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=127,
)


_ADDUSERREQ = _descriptor.Descriptor(
  name='AddUserReq',
  full_name='user.AddUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='user.AddUserReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='user.AddUserReq.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='user.AddUserReq.gender', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=189,
)


_UPDATEUSERREQ = _descriptor.Descriptor(
  name='UpdateUserReq',
  full_name='user.UpdateUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='user.UpdateUserReq.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='user.UpdateUserReq.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='user.UpdateUserReq.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='user.UpdateUserReq.gender', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=271,
)


_DELETEUSERREQ = _descriptor.Descriptor(
  name='DeleteUserReq',
  full_name='user.DeleteUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='user.DeleteUserReq.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=305,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['DataRes'] = _DATARES
DESCRIPTOR.message_types_by_name['AddUserReq'] = _ADDUSERREQ
DESCRIPTOR.message_types_by_name['UpdateUserReq'] = _UPDATEUSERREQ
DESCRIPTOR.message_types_by_name['DeleteUserReq'] = _DELETEUSERREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'proto.user.user_pb2'
  # @@protoc_insertion_point(class_scope:user.User)
  ))
_sym_db.RegisterMessage(User)

DataRes = _reflection.GeneratedProtocolMessageType('DataRes', (_message.Message,), dict(
  DESCRIPTOR = _DATARES,
  __module__ = 'proto.user.user_pb2'
  # @@protoc_insertion_point(class_scope:user.DataRes)
  ))
_sym_db.RegisterMessage(DataRes)

AddUserReq = _reflection.GeneratedProtocolMessageType('AddUserReq', (_message.Message,), dict(
  DESCRIPTOR = _ADDUSERREQ,
  __module__ = 'proto.user.user_pb2'
  # @@protoc_insertion_point(class_scope:user.AddUserReq)
  ))
_sym_db.RegisterMessage(AddUserReq)

UpdateUserReq = _reflection.GeneratedProtocolMessageType('UpdateUserReq', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEUSERREQ,
  __module__ = 'proto.user.user_pb2'
  # @@protoc_insertion_point(class_scope:user.UpdateUserReq)
  ))
_sym_db.RegisterMessage(UpdateUserReq)

DeleteUserReq = _reflection.GeneratedProtocolMessageType('DeleteUserReq', (_message.Message,), dict(
  DESCRIPTOR = _DELETEUSERREQ,
  __module__ = 'proto.user.user_pb2'
  # @@protoc_insertion_point(class_scope:user.DeleteUserReq)
  ))
_sym_db.RegisterMessage(DeleteUserReq)



_USERAPI = _descriptor.ServiceDescriptor(
  name='UserApi',
  full_name='user.UserApi',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=308,
  serialized_end=467,
  methods=[
  _descriptor.MethodDescriptor(
    name='addUser',
    full_name='user.UserApi.addUser',
    index=0,
    containing_service=None,
    input_type=_ADDUSERREQ,
    output_type=_DATARES,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='updateUser',
    full_name='user.UserApi.updateUser',
    index=1,
    containing_service=None,
    input_type=_UPDATEUSERREQ,
    output_type=_DATARES,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteUser',
    full_name='user.UserApi.deleteUser',
    index=2,
    containing_service=None,
    input_type=_DELETEUSERREQ,
    output_type=_DATARES,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERAPI)

DESCRIPTOR.services_by_name['UserApi'] = _USERAPI

# @@protoc_insertion_point(module_scope)
