# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import user_pb2 as proto_dot_user_dot_user__pb2


class UserApiStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addUser = channel.unary_unary(
        '/user.UserApi/addUser',
        request_serializer=proto_dot_user_dot_user__pb2.AddUserReq.SerializeToString,
        response_deserializer=proto_dot_user_dot_user__pb2.DataRes.FromString,
        )
    self.updateUser = channel.unary_unary(
        '/user.UserApi/updateUser',
        request_serializer=proto_dot_user_dot_user__pb2.UpdateUserReq.SerializeToString,
        response_deserializer=proto_dot_user_dot_user__pb2.DataRes.FromString,
        )
    self.deleteUser = channel.unary_unary(
        '/user.UserApi/deleteUser',
        request_serializer=proto_dot_user_dot_user__pb2.DeleteUserReq.SerializeToString,
        response_deserializer=proto_dot_user_dot_user__pb2.DataRes.FromString,
        )


class UserApiServicer(object):
  """The greeting service definition.
  """

  def addUser(self, request, context):
    """Sends a greeting
    rpc SayHello (HelloRequest) returns (HelloReply) {}
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addUser': grpc.unary_unary_rpc_method_handler(
          servicer.addUser,
          request_deserializer=proto_dot_user_dot_user__pb2.AddUserReq.FromString,
          response_serializer=proto_dot_user_dot_user__pb2.DataRes.SerializeToString,
      ),
      'updateUser': grpc.unary_unary_rpc_method_handler(
          servicer.updateUser,
          request_deserializer=proto_dot_user_dot_user__pb2.UpdateUserReq.FromString,
          response_serializer=proto_dot_user_dot_user__pb2.DataRes.SerializeToString,
      ),
      'deleteUser': grpc.unary_unary_rpc_method_handler(
          servicer.deleteUser,
          request_deserializer=proto_dot_user_dot_user__pb2.DeleteUserReq.FromString,
          response_serializer=proto_dot_user_dot_user__pb2.DataRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'user.UserApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
